#Minecraft server properties
#Sun Apr 26 17:39:05 PDT 2026
accepts-transfers=false
allow-flight=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=https\://support.mattfaulkner.net/
difficulty=easy
enable-code-of-conduct=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=true
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=adventure
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world_maple_2026
level-seed=-7649949940957896961
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=KBdRYXzVveFgCDnyXI5otEkvCx0XzbkzMsyJXY2C
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=1000000
max-players=6
max-tick-time=60000
max-world-size=29999984
motd=Crafting At Home
network-compression-threshold=256
online-mode=true
op-permission-level=4
pause-when-empty-seconds=60
player-idle-timeout=0
prevent-proxy-connections=false
query.port=25565
rate-limit=0
rcon.password=$RCON_PASSWORD
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=https://cdn.modrinth.com/data/r4GILswZ/versions/yjAqtxxY/Faithful%2064x%20-%20Release%2013.zip
resource-pack-id=
resource-pack-prompt=Placeholder1
resource-pack-sha1=06f37fc2febd487e5b94a1d93858c50ae8c8ca51
server-ip=0.0.0.0
server-port=25565
simulation-distance=8
spawn-protection=8
status-heartbeat-interval=0
sync-chunk-writes=true
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=24
white-list=true
